apiVersion : apps/v1
kind : Deployment
metadata:
  name : abhishek-deployment
  labels:
    first: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: fitness
          image: abhishekjoshhi/fitness:v1.0.0
          ports:
            - containerPort: 5000
        - name : nginx
          image: nginx:latest
          ports:
            - containerPort: 800