apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: abhishek-replicaset
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      web: ghee
  template:
    metadata:
      labels:
        web: ghee
    spec:
      containers:
        - name: ghee
          image: abhishekjoshhi/ghee
          ports:
            - containerPort: 5656